---
- name: Desescalado de la APPx-API
  hosts: localhost
  become: yes

  vars:
    replicas: 3  

  tasks:
    - name: Detener contenedores de APPx-API para desescalado
      command: >
        docker stop appx-api-{{ item }}
      loop: "{{ range(1, replicas +1) | list }}"   

    - name: Eliminar contenedores de APPx-API para desescalado
      command: >
        docker rm -f appx-api-{{ item }}
      loop: "{{ range(1, replicas + 1) | list }}"  